MOSIP-22976: Updated messaged_ara.properties
mosip/keycloak pull request #26
Opened 2022-09-05 04:55 UTC by balaji-alluru

2022-09-07 11:53 UTC, gsasikumar approved these changes

2022-09-07 11:53 UTC, gsasikumar commented on keycloak-jboss/theme/base/login/messages/messages_ara.properties
> +openshift.scope.user_info=معلومات المستخدم
Is this openshift specific?

2022-09-08 05:26 UTC, ckm007 requested changes
we are no more using keycloak-jboss.
we are now using keycloak-artemis.. so can we have the same change there as well.

2022-09-08 06:17 UTC, balaji-alluru commented
> we are no more using keycloak-jboss. we are now using keycloak-artemis.. so can we have the same change there as well.

2022-09-08 06:17 UTC, closed without merging